### ISSUE TITLE
[Bug] Keychron K3 locks up or spam keys

### ISSUE THREAD

**Issue by card78** [SonixQMK/qmk_firmware#304]
## System Information

 - Keyboard:  
   - Revision (if applicable):  Keychron K3 V2 RGB optical ANSI
 - Operating system: Compiled on Mac. Tested on Mac and Windows.
 - AVR GCC version: 8.5.0

 - ARM GCC version: 8.3.1

 - QMK Firmware version: 0.7.101

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context
This is related to #271. If you revert https://github.com/SonixQMK/qmk_firmware/commit/238e200904f2ccea5de10bddb70ac07845e5830d, the bug goes away.

**Comment by patriksh** [comment]
@card78 any updates on your end? I'm having a similar issue.

**Comment by starptr** [comment]
Reverting `238e200` no longer fixes this issue; I guess there's been new commits to `sn32_master` branch of the chibios-contrib repo that causes this

@card78 which commits did you check out for this repo (SonixQMK/qmk_firmware) and the submodules such that this issue doesn't appear?

Edit: oops I was not debugging correctly; looks like reverting that particular commit does fix it for me.

**Comment by sambartle** [comment]
I'm currently trying to support a new keyboard and I believe I might be having a similar issue.. 

I get the same thing.. if you press some combinations of multiple keys, youll fairly quickly get either a lock up, or one of the keys you pressed just repeating constantly until you unplug the keyboard. 

If you don't do that.. it will work fine forever and all keys and led's respond as expected, so the matrix seems fine, and the software seems to be working fine. 

I've tried reverting the change and pulling the sn32_master branch (as well as the sn32 one) and still have the issue though. 

The linked issue refers to a timer issue.. anyone have any details on exactly what that issue is so i might try and debug this please?

**Comment by humbertogontijo** [comment]
Is the k3 pro anything related to k3v2? If so, a lot could be taken from https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/k3_pro

**Comment by patriksh** [comment]
Correct me if I'm wrong, but I believe the K3 Pro has a completely different MCU (STM32 on the Pro, SN32 on the V2).

**Comment by dexter93** [comment]
See https://github.com/SonixQMK/qmk_firmware/issues/336
